apiVersion: skaffold/v4beta6
kind: Config
build:
  # local:
  #   push: false
  googleCloudBuild:
    projectId: orbital-dev-402212
  artifacts:
    - image: gcr.io/orbital-dev-402212/auth
      context: auth
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - ./infra/k8s/*
deploy:
  kubectl: {}
